version: '3.9'

services:
  web:
    container_name: bns_web
    build: /home/bns/web2/.
    depends_on:
    - db
    volumes:
    - my-vol_web:/var/www/html/file
    ports:
    - 80:80  
  db:
    container_name: bns_db
    build: /home/bns/mysql/.
    volumes:
    - my-vol_db:/var/lib/mysql/
    ports:
    - 3306:3306
  phpadmin:
    container_name: bns_php_admin
    image: phpmyadmin
    depends_on:
    - db
    ports:
    - 8080:80
volumes:
  my-vol_web:
  my-vol_db:
  



      
